# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkID=615560

name: 'CTest (arm64)'

on:
  push:
    branches: "main"
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.azuredevops/**'
      - '.nuget/*'
      - build/*.ps1
  pull_request:
    branches: "main"
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.azuredevops/**'
      - '.nuget/*'
      - build/*.ps1

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-11-arm
    timeout-minutes: 20

    strategy:
      fail-fast: false

      matrix:
        build_type: [arm64-Release]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Clone test repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: walbourn/directxmathtest
          path: Tests
          ref: main

      - name: 'Install Ninja'
        run: choco install ninja

      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch: arm64

      - name: 'Configure CMake'
        working-directory: ${{ github.workspace }}
        run: cmake --preset=${{ matrix.build_type }} -DBUILD_TESTING=ON

      - name: 'Build'
        working-directory: ${{ github.workspace }}
        run: cmake --build out/build/${{ matrix.build_type }}

      - timeout-minutes: 10
        name: 'Test'
        working-directory: ${{ github.workspace }}
        run: ctest --preset=${{ matrix.build_type }} --output-on-failure
